"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog"
import { FileText, Download } from "lucide-react"

interface PricingRow {
  sku: string
  description: string
  quantity: string
  unitPrice: number
  testCost: number
  lineTotal: number
}

const pricingData: PricingRow[] = [
  {
    sku: "AP-CAB-4C-50XLPE",
    description: "4 Core LT Power Cable 50 sq.mm Aluminium 1.1kV XLPE",
    quantity: "2000 m",
    unitPrice: 450,
    testCost: 500,
    lineTotal: 900500,
  },
  {
    sku: "AP-CAB-3P5C-120XLPE",
    description: "3.5 Core LT Power Cable 120 sq.mm Aluminium 1.1kV XLPE",
    quantity: "1200 m",
    unitPrice: 820,
    testCost: 800,
    lineTotal: 985600,
  },
  {
    sku: "CTRL-12C-2.5PVC",
    description: "12 Core Control Cable 2.5 sq.mm Copper 1.1kV PVC",
    quantity: "1000 m",
    unitPrice: 150,
    testCost: 300,
    lineTotal: 150300,
  },
]

export function PricingSection() {
  const [isDialogOpen, setIsDialogOpen] = useState(false)

  const materialTotal = pricingData.reduce((sum, row) => sum + row.unitPrice * Number.parseFloat(row.quantity), 0)
  const testingTotal = pricingData.reduce((sum, row) => sum + row.testCost, 0)
  const grandTotal = pricingData.reduce((sum, row) => sum + row.lineTotal, 0)

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
      maximumFractionDigits: 0,
    }).format(amount)
  }

  const handleGenerateProposal = () => {
    setIsDialogOpen(true)
  }

  const handleDownloadPdf = () => {
    alert("PDF download would be triggered in production. File: SmartRFP_Proposal_RFP-2025-001.pdf")
  }

  return (
    <>
      <Card>
        <CardHeader>
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2">
                <CardTitle className="text-2xl font-bold text-slate-900">
                  Pricing & Proposal Assembly (Pricing Agent)
                </CardTitle>
                <Badge className="bg-green-100 text-green-700">Generated by Pricing & Report Generator Agent</Badge>
              </div>
              <p className="mt-1 text-sm text-slate-500">
                Pricing teams currently wait for specs, then manually build Excel sheets. SmartRFP consolidates
                materials and test costs automatically.
              </p>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="overflow-hidden rounded-lg border border-slate-200">
            <table className="w-full">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-slate-700">
                    SKU
                  </th>
                  <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-slate-700">
                    Description
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium uppercase tracking-wider text-slate-700">
                    Quantity
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium uppercase tracking-wider text-slate-700">
                    Unit Price
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium uppercase tracking-wider text-slate-700">
                    Test Cost
                  </th>
                  <th className="px-6 py-3 text-right text-xs font-medium uppercase tracking-wider text-slate-700">
                    Line Total
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {pricingData.map((row, index) => (
                  <tr key={row.sku} className={index % 2 === 1 ? "bg-slate-50" : ""}>
                    <td className="whitespace-nowrap px-6 py-4 text-sm font-medium text-slate-900">{row.sku}</td>
                    <td className="px-6 py-4 text-sm text-slate-700">{row.description}</td>
                    <td className="whitespace-nowrap px-6 py-4 text-right text-sm text-slate-700">{row.quantity}</td>
                    <td className="whitespace-nowrap px-6 py-4 text-right text-sm text-slate-700">
                      {formatCurrency(row.unitPrice)}
                    </td>
                    <td className="whitespace-nowrap px-6 py-4 text-right text-sm text-slate-700">
                      {formatCurrency(row.testCost)}
                    </td>
                    <td className="whitespace-nowrap px-6 py-4 text-right text-sm font-semibold text-slate-900">
                      {formatCurrency(row.lineTotal)}
                    </td>
                  </tr>
                ))}
              </tbody>
              <tfoot className="bg-slate-100">
                <tr>
                  <td colSpan={5} className="px-6 py-4 text-right text-sm font-semibold text-slate-900">
                    Material Total:
                  </td>
                  <td className="whitespace-nowrap px-6 py-4 text-right text-sm font-bold text-slate-900">
                    {formatCurrency(materialTotal)}
                  </td>
                </tr>
                <tr>
                  <td colSpan={5} className="px-6 py-4 text-right text-sm font-semibold text-slate-900">
                    Testing Total:
                  </td>
                  <td className="whitespace-nowrap px-6 py-4 text-right text-sm font-bold text-slate-900">
                    {formatCurrency(testingTotal)}
                  </td>
                </tr>
                <tr className="bg-blue-50">
                  <td colSpan={5} className="px-6 py-4 text-right text-base font-bold text-slate-900">
                    Grand Total:
                  </td>
                  <td className="whitespace-nowrap px-6 py-4 text-right text-base font-bold text-blue-700">
                    {formatCurrency(grandTotal)}
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>

          <div className="mt-6 flex justify-end">
            <Button onClick={handleGenerateProposal} size="lg" className="gap-2 bg-blue-600 hover:bg-blue-700">
              <FileText className="h-5 w-5" />
              Generate Proposal
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Proposal Dialog */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="text-xl font-bold text-slate-900">Proposal Ready</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="rounded-lg bg-slate-50 p-4">
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="font-medium text-slate-700">Client:</span>
                  <p className="mt-1 text-slate-900">NTPC Power Limited</p>
                </div>
                <div>
                  <span className="font-medium text-slate-700">RFP ID:</span>
                  <p className="mt-1 text-slate-900">RFP-2025-001</p>
                </div>
                <div>
                  <span className="font-medium text-slate-700">Grand Total:</span>
                  <p className="mt-1 text-lg font-bold text-blue-700">{formatCurrency(grandTotal)}</p>
                </div>
                <div>
                  <span className="font-medium text-slate-700">Processing Time:</span>
                  <p className="mt-1 text-slate-900">Under 5 minutes</p>
                </div>
              </div>
            </div>
            <div className="rounded-lg border border-blue-200 bg-blue-50 p-4">
              <p className="text-sm text-blue-900">
                <strong>SmartRFP</strong> assembled a draft proposal in under 5 minutes vs 3 days manually. The proposal
                includes product specifications, test certifications, and comprehensive pricing.
              </p>
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
              Close
            </Button>
            <Button onClick={handleDownloadPdf} className="gap-2 bg-blue-600 hover:bg-blue-700">
              <Download className="h-4 w-4" />
              Download PDF
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  )
}
